version: "3"

volumes:
 onboarding_bot_postgres_data: {}
 onboarding_bot_postgres_data_backups: {}

services:
 postgres:
   build:
     context: .
     dockerfile: ./compose/production/postgres/Dockerfile
   image: onboarding_bot_production_postgres
   container_name: onboarding_bot_local_postgres
   volumes:
     - onboarding_bot_postgres_data:/var/lib/postgresql/data
     - onboarding_bot_postgres_data_backups:/backups
   env_file:
     - ./.envs/.postgres
   ports:
     - "5442:5432"
 web:
    build: .
    container_name: onboarding_bot
    command: python main.py
    ports:
      - 3001:3001
    volumes:
      - ./:/app
    env_file:
      - .envs/.bot
    depends_on:
     - postgres
