version: "3"


services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: "onboarding_bot_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../Init_Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5442:5442"
  web:
    build: .
    container_name: onboarding_bot
    command: python main.py
    ports:
      - 3001:3001
    volumes:
      - ./:/app
    env_file:
      - .envs/.bot
    depends_on:
      - postgres
